name: literasi_digital_tuna_netra
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  animated_splash_screen: ^1.3.0
  lottie: ^2.2.0
  google_fonts: ^4.0.3
  camera: ^0.10.3+2
  google_mlkit_text_recognition: ^0.5.0
  permission_handler: ^10.2.0
  flutter_tts: ^3.6.3
  qr_code_scanner: ^1.0.1
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  intl: ^0.18.1
  dropdown_search: ^5.0.6
  firebase_storage: ^11.2.1
  image_picker: ^0.8.7+5
  line_awesome_flutter: ^2.0.0
  get_cli: ^0.2.30




dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
   - assets/
   - assets/images/